default: &default
  adapter: postgresql
  encoding: unicode
  host: ec2-3-95-130-249.compute-1.amazonaws.com
  username: nzohgeboghezyt
  password: 56414ae0f53722bb8cc76353d3fceb5fdc004635a47918d7a0e13de899e291e6
  pool: 5

development:
  <<: *default
  database: d9obkh97ailf0g

test:
  <<: *default

production:
  <<: *default
  database: d9obkh97ailf0g

